general {
    grace = 0
    disable_loading_bar = true
}

background {
    monitor =
    color = rgba(0, 0, 0, 1.0)
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.3
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(255,255,255,0.2)
    inner_color = rgba(0,0,0,0.5)
    font_color = rgba(255,255,255,1.0)
}
